### ISSUE TITLE
Çalıştırma Hatası

### ISSUE THREAD

**Issue by ghost** [teknofest-suruiha/suruiha#3]
Merhabalar.
Wiki bölümünden tüm adımları takip ettim fakat çalıştırmaya çalışınca aşağıdaki hataları alıyorum.
```
m@u:~$ roslaunch uav_gazebo zephyr_runway.launchWARNING: unable to configure logging. No log files will be generated
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Invalid <param> tag: Cannot load command parameter [rosversion]: command [rosversion roslaunch] returned with code [1]. 

Param xml is <param command="rosversion roslaunch" name="rosversion"/>
The traceback for the exception was written to the log file
No handlers could be found for logger "roslaunch"
m@u:~$ 
```
Bir başka hata daha:
```
m@u:~$ rosrun uav_ground_control keyboard_control.py _pose:=iris0_pose _control:=iris0_control 
Traceback (most recent call last):
  File "/home/m/catkin_ws/src/suruiha/uav_ground_control/scripts/keyboard_control.py", line 24, in <module>
    rospy.init_node('uav_keyboard_control', anonymous=True)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 309, in init_node
    rospy.core.configure_logging(resolved_node_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 299, in configure_logging
    _log_filename = rosgraph.roslogging.configure_logging('rospy', level, filename=filename)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 113, in configure_logging
    rosgraph_d = rospkg.RosPack().get_path('rosgraph')
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: rosgraph
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/m/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share/home/m/catkin_ws/src
m@u:~$ 
```
Güncellediğim bashrc kaydımın son satırları ise aşağıda:
```
source /opt/ros/kinetic/setup.bash
source /home/m/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH/home/m/catkin_ws/src
export GAZEBO_MODEL_PATH=/home/m/catkin_ws/src/suruiha/uav_description/gazebo_models/
export GAZEBO_PLUGIN_PATH=/home/m/catkin_ws/devel/lib/
```
Bu sorunu nasıl çözebilirim?

**Comment by gokceuludogan** [comment]
Merhaba,
Dokümantasyonda ufak bir hata olmuş. 
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH/home/elif/catkin_ws/src` satırını 
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/elif/catkin_ws/src` ile değiştirip tekrar deneyebilir misiniz?

**Comment by okanasik** [comment]
Yapılan son bilgilendirmeden sonra kurulumun başarıyla gerçekleştiğini varsayıyorum. Eğer hala sorunlar yaşıyorsanız, lütfen yeni bir hata veya destek bildirimi yapın.
